---
- name: Install Apache
  hosts: all
  become: true
  
  tasks: 
    - name: Install Apache.
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Copy configuration files.
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - src: httpd.conf
          dest: /etc/httpd/conf/httpd.conf
        - src: httpd-vhosts.conf
          dest: /etc/httpd/conf/httpd-vhosts.conf
    
    - name: Make sure apache is started now and at boot
      service:
        name: httpd
        state: started
        enable: true
