---
- name: Install Apache
  hosts: all
  become: true
  
  pre_tasks:
   - name: Update apt cache if needed
     apt: 
       update_cache: true
       cache_valid_time: 3600

  tasks: 
    - name: Install Apache.
      apt:
        name: apache2
        state: present

    - name: Copy configuration files.
      copy:
        src: apache2.conf
        dest: /etc/apache2/apache2.conf
    
    - name: Make sure apache is started now and at boot
      service:
        name: apache2
        state: started
        enabled: true
