---
- name: Install alacritty terminfo
  hosts: all
  gather_facts: no

  tasks:
    - name: Verify if it is loaded
      shell: toe -s -a | grep "alacritty"
      register: toe_output
      ignore_errors: true

    - name: print toe
      debug:
        var: toe_output.rc

    - name: Fail if alacritty terminfo is already loaded
      fail:
        msg: "Alacritty terminfo is already installed"
      when: toe_output.rc == 0

    - name: Download alacritty terminfo
      get_url:
        url: https://raw.githubusercontent.com/alacritty/alacritty/master/extra/alacritty.info
        dest: /tmp/alacritty.info
        mode: '0644'

    - name: Load alacritty terminfo
      command: tic -xe alacritty,alacritty-direct /tmp/alacritty.info
      become: yes
      when: toe_output.rc == 1
