---
- hosts: all
  become: true

  vars:
    ssh_path: /home/eycer/.ssh/

  handlers:
    - name: restart ssh
      service:
        name: sshd
        state: restarted

  tasks:
    - name: Update SSH config.
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        validate: 'sshd -T -f %s'
      loop:
        - regexp: "^PasswordAuthentication"
          line: "PasswordAuthentication no"
        - regexp: "^PermitRootLogin"
          line: "PermitRootLogin no"
      notify: restart ssh

    - name: Make sure handlers are flushed.
      meta: flush_handlers

    - name: Add user eycer.
      user:
        name: eycer

    - name: Add sudo group rights for deployment user.
      lineinfile:
        dest: /etc/sudoers
        regexp: "^eycer"
        line: "eycer ALL=(ALL) NOPASSWD:ALL"
        state: present
        validate: 'visudo -cf %s'

    # Add master key
    - name: Authorize the ssh key
      ansible.posix.authorized_key:
        user: eycer
        state: present
        key: "{{ lookup('file', ssh_path + 'master_key.pub') }}"
