---
- name: "Playbook to install all home media server containers"
  hosts: test

  pre_tasks:
   - name: Update apt cache if needed
     package:
       update_cache: true
     become: true

   - name: Create folders structure
     ansible.builtin.file:
       path: "{{ item }}"
       state: directory
       owner: eycer
       group: eycer
       mode: '0755'

     loop:
       - /opt/jellyfin/config
       - /opt/jellyfin/tvshows
       - /opt/jellyfin/anime
       - /opt/jellyfin/movies
       - /opt/jellyfin/animovies
       - /opt/jellyfin/kdrama
       - /opt/transmission/config
       - /opt/transmission/downloads
       - /opt/transmission/watch
       - /opt/sonarr/config
       - /opt/radarr/config
       - /opt/bazarr/config
       - /opt/jackett/config
       - /opt/jellyseerr/config
     become: true

  tasks:
    - name: Install podman
      ansible.builtin.package:
        name: podman
        state: present
      become: true
   
    - name: Create containers.conf
      ansible.builtin.file:
        path: /etc/containers/containers.conf
        state: touch
        owner: root
        group: root
        mode: '0644'
      become: true

    - name: Configure cgroup
      ansible.builtin.blockinfile:
        path: /etc/containers/containers.conf
        block: |
          [engine]
          cgroup_manager = "cgroupfs"
          events_logger = "file"
      become: true


    - name: Create mediapod pod
      containers.podman.podman_pod:
        name: mediapod
        state: created
        ports:
          - "8096:8096"

    - name: Create jellyfin container
      containers.podman.podman_container:
        name: jellyfin
        image: lscr.io/linuxserver/jellyfin:latest
        pod: mediapod
        volume: 
          - /opt/jellyfin/config:/config
          - /opt/jellyfin/tvshows:/data/tvshows
          - /opt/jellyfin/anime:/data/anime
          - /opt/jellyfin/movies:/data/movies
          - /opt/jellyfin/animovies:/data/animovies
          - /opt/jellyfin/kdrama:/data/kdrama
        env:
            PUID: 1000
            PGID: 1000
            TZ: America/Argentina/Buenos_Aires
        label: "io.containers.autoupdate=image"
        state: created

    - name: Create systemd service for mediapod
      containers.podman.podman_generate_systemd:
        name: mediapod
        new: true
        dest: ~/.config/systemd/user

    - name: Start the mediapod service
      ansible.builtin.systemd:
        name: pod-mediapod.service
        daemon_reload: true
        scope: user
        state: started
        enabled: true
        
